version: '2'
services:
    nginx:
      image: nginx:alpine
      container_name: "project-nginx"
      volumes:
        - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
        - ./docker/nginx/cert.pem:/etc/nginx/sslcreds/cert.pem
        - ./docker/nginx/key.pem:/etc/nginx/sslcreds/key.pem
      ports:
        - "80:80"
        - "443:443"

    project-php:
        build: docker/php
        container_name: "project-php"
        ports:
          - "80"
        volumes:
          - ./docker/php/src:/var/www

    project-db:
        build: docker/db
        container_name: "project-db"
        ports:
          - "80"
        volumes:
          - ./docker/db/src:/var/www

    project-database:
        container_name: "project-database"
        image: onjin/alpine-postgres:9.5
        restart: unless-stopped
        ports:
            - "5432:5432"
        environment:
            LC_ALL: C.UTF-8
            POSTGRES_USER: docker_test
            POSTGRES_PASSWORD: docker_test
            POSTGRES_DB: docker_test
